name: instagram_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: 2.3.10
  steps_indicator: ^1.3.0
  google_fonts: 6.1.0
  url_launcher: ^6.2.6
  sticky_headers: ^0.3.0+2
  cached_network_image: ^3.3.1
  firebase_core: ^2.27.0
  flutter_bloc: ^8.1.5
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  uuid: ^4.4.0
  firebase_storage: ^11.6.9
  awesome_snackbar_content: ^0.1.3
  file_picker: ^8.0.0+1
  shared_preferences: ^2.2.3
  photo_manager: ^3.1.1
  photo_manager_image_provider: ^2.1.1
  camera: ^0.11.0+1
  image: ^4.2.0
  video_player: ^2.8.7
  gradient_borders: ^1.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/instagram_app_icon.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  # color: '#ffffff'
  image: 'assets/images/insta.png'
  background_image: 'assets/images/splash_image_background.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/insta.png
    - assets/images/meta_group.png
    - assets/images/splash_image_background.png
    - assets/images/onboarding_image_1.png
    - assets/images/onboarding_image_2.png
    - assets/images/onboarding_image_3.png
    - assets/images/onboarding_image_4.png
    - assets/images/insta_black_logo.png
    - assets/icons/facebook_icon.png
    - assets/icons/google_icon.png
    - assets/icons/green_tick_icon.png
    - assets/icons/password_hidden_eye_icon.png
    - assets/icons/password_shown_eye_icon.png
    - assets/icons/password_lock_icon.png
    - assets/icons/user_icon.png
    - assets/icons/home_feed_rounded_icon.png
    - assets/icons/explore_rounded_icon.png
    - assets/icons/reels_rounded_icon.png
    - assets/icons/notification_rounded_icon.png
    - assets/icons/user_profile_rounded_icon.png
    - assets/icons/active_explore_icon.png
    - assets/icons/active_home_feed_icon.png
    - assets/icons/active_notification_icon.png
    - assets/icons/active_reels_icon.png
    - assets/icons/active_user_profile_icon.png
    - assets/icons/account_list_dropdown_icon.png
    - assets/icons/add_medium_button_icon.png
    - assets/icons/instagram_rounded_icon.png
    - assets/icons/private_account_icon.png
    - assets/icons/side_menu_icon.png
    - assets/icons/grid_select.png
    - assets/icons/grid_unselect.png
    - assets/icons/mention_select.png
    - assets/icons/mention_unselect.png
    - assets/icons/flash_icon.png
    - assets/icons/no_flash_icon.png
    - assets/icons/swap_camera_icon.png
    - assets/icons/archive_icon.png
    - assets/icons/activity_icon.png
    - assets/icons/close_friend_list_icon.png
    - assets/icons/covid_center_icon.png
    - assets/icons/discover_people_icon.png
    - assets/icons/nametag_icon.png
    - assets/icons/open_facebook_icon.png
    - assets/icons/saved_post_icon.png
    - assets/icons/setting_icon.png
    - assets/icons/camera_icon.png
    - assets/icons/add_feed_button_icon.png
    - assets/icons/message_icon.png
    - assets/icons/like_icon.png
    - assets/icons/liked_icon.png
    - assets/icons/comment_icon.png
    - assets/icons/save_icon.png
    - assets/icons/saved_icon.png
    - assets/icons/share_icon.png
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-HeavyItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.otf
          weight: 200
          style: italic